name: Code Formatter and Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install black isort flake8

      - name: Run isort to sort imports
        run: isort . --quiet

      - name: Run Black with check
        run: black . --check --quiet

      - name: Run Flake8
        run: flake8 .

      - name: Show diff if formatting was needed
        run: |
          git diff || echo "No formatting changes"
          exit 0

  # type-check:
  #   runs-on: ubuntu-latest
  #   needs: format-and-lint

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5.2.0
  #       with:
  #         python-version: "3.10"

  #     - name: Install dependencies for mypy
  #       run: make setup_dev

  #     - name: Run mypy
  #       run: mypy .
