name: Python Release to GitHub

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["Code Formatter and Linter"]
    branches: [main]
    types:
      - completed

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build release distributions
        run: poetry build

      - name: Upload distributions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🎉 **New Release: ${{ github.ref_name }}** 🎉
            - Automatically generated release using GitHub Actions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
